// List of all sectors for multi-select dropdown
export const SECTORS = [
  "Agriculture, Forestry and Fishing",
  "Mining and Quarrying",
  "Oil and Gas",
  "Energy and Utilities (Electricity, Gas, Water)",
  "Renewable Energy",
  "Manufacturing and Industrial Production",
  "Chemicals and Materials",
  "Construction and Infrastructure",
  "Real Estate and Property Management",
  "Transportation and Logistics",
  "Automotive and Mobility Services",
  "Retail and Wholesale Trade",
  "Consumer Goods and Products",
  "Food and Beverage Production / Processing",
  "Textiles, Apparel and Footwear",
  "Technology, Software and IT Services",
  "Telecommunications and Digital Services",
  "Financial Services (Banking, Finance, FinTech)",
  "Insurance",
  "Professional, Scientific and Technical Services",
  "Media, Marketing and Advertising",
  "Hospitality, Tourism and Leisure",
  "Healthcare and Medical Services",
  "Education and Training Services",
  "Waste Management and Recycling",
  "Water and Sanitation Services",
  "Public Sector / Government Organizations",
  "Non-Profit Organizations / NGOs",
  "Other (Please Specify)"
];
